# Generated by Django 3.2.9 on 2021-12-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[['MALE', 'Male'], ['FEMAIL', 'Femail']], max_length=10)),
                ('adhaar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app2.person')),
                ('dno', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
            bases=('app2.person',),
        ),
    ]
