# Generated by Django 3.2.9 on 2021-12-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[['MALE', 'Male'], ['FEMALE', 'Female']], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('attend', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('adhaar', models.BigIntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='nontech',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app4.person')),
                ('design', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
            bases=('app4.person',),
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app4.person')),
                ('course', models.CharField(max_length=20)),
                ('fee', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            bases=('app4.person',),
        ),
        migrations.CreateModel(
            name='tech',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app4.person')),
                ('design', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
            bases=('app4.person',),
        ),
    ]
