# Generated by Django 3.2.9 on 2021-12-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='scc',
            new_name='ssc',
        ),
    ]
