# Generated by Django 3.2.9 on 2021-12-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nontech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[['MALE', 'Male'], ['FEMALE', 'Female']], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('attend', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('adhaar', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('design', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[['MALE', 'Male'], ['FEMALE', 'Female']], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('attend', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('adhaar', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('course', models.CharField(max_length=20)),
                ('fee', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[['MALE', 'Male'], ['FEMALE', 'Female']], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('attend', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('adhaar', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('design', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
